applications:
    app:
        # The type of the application to build.
        type: 'python:3.8'
        # Environment variables available to the app container.
        variables:
            env:
                MEILISEARCH_VERSION: 'v0.15.0'
                TEMPLATE_DEMO: true
                POETRY_VERSION: '1.1.4'
                POETRY_VIRTUALENVS_IN_PROJECT: true
                POETRY_VIRTUALENVS_CREATE: false
        # The hooks that will be performed when the package is deployed.
        hooks:
            build: !include
                type: string
                path: build.sh
            deploy: .poetry/bin/poetry run python update_demo_index.py
        # The configuration of app when it is exposed to the web.
        web:
            commands:
                # Run the Meilisearch server
                start: "./meilisearch --http-addr localhost:${PORT}"
        # The mounts that will be performed when the package is deployed.
        mounts:
            "data.ms":
                source: storage
                source_path: "datams"
        source:
            root: /files/search/
services: null
routes: null
